name: ade20k_ona
distinct: true
offset: -1
groups:
  - {name: Unknown, labels: [24, 40, 50, 70, 79, 98, 110, 114, 82, 93, 132, 38, 48,
      51, 66, 72, 108, 119, 125, 130, 134, 146, 147,
      68, 75, 90, 109, 120, 128, 131, 133, 138, 139, 
      142, 144, 99, 121, 126, 136, 143, 148]}
  - {name: Sky, labels: [3]}
  - {name: Tree, labels: [5, 73]}
  - {name: Water, labels: [22, 27, 61, 129]}
  - {name: Ground, labels: [10, 14, 30, 47, 95]}
  - {name: Sidewalk, labels: [12, 141]}
  - {name: Road, labels: [7, 53, 55, 92]}
  - {name: Vehicle, labels: [21, 81, 84, 91, 103, 117]}
  - {name: Building, labels: [2, 26, 49, 52, 80, 85, 115]}
  - {name: Signal, labels: [137]}
  - {name: Rock, labels: [35]}
  - {name: Fence, labels: [33]}
  - {name: Boat, labels: [77, 104]}
  - {name: Sign, labels: [124]}
  - {name: Slope, labels: [17, 69]}
  - {name: Bridge, labels: [62]}
  - {name: Wall, labels: [1]}
  - {name: Floor, labels: [4, 29, 102, 106]}
  - {name: Ceiling, labels: [6, 87, 107]}
  - {name: Door, labels: [15, 59]}
  - {name: Stairs, labels: [54, 60, 97, 122]}
  - {name: Structure, labels: [19, 39, 41, 43, 64, 89, 94, 96, 105, 123]}
  - {name: Window, labels: [9]}
  - {name: Plant, labels: [18, 67, 136]}
  - {name: Furniture, labels: [16, 34, 46, 57, 65, 20, 31, 32, 76, 111, 
      11, 36, 42, 45, 56, 112, 113, 116, 8, 58, 118,
      25, 63, 71, 74, 78, 100]}
  - {name: Wall_Decoration, labels: [23, 28, 44, 101, 145, 149, 150, 37, 83, 86, 88, 135, 140]}
  - {name: Dynamic_NonHuman, labels: [127]}
  - {name: Human, labels: [13]}
specified_colors:
  - {name: Sky, source: raw_int, color: [102, 178, 255]}
  - {name: Ceiling, source: raw_int, color: [102, 178, 255]}
  - {name: Water, source: raw_int, color: [0, 0, 255]}
  - {name: Tree, source: raw_int, color: [0, 255, 0]}
  - {name: Plant, source: raw_int, color: [0, 102, 0]}
  - {name: Vehicle, source: raw_int, color: [204, 0, 0]}
  - {name: Rock, source: raw_int, color: [0, 102, 0]}
  - {name: Ground, source: raw_int, color: [255, 255, 255]}
  - {name: Bridge, source: raw_int, color: [255, 255, 255]}
  - {name: Slope, source: raw_int, color: [192, 192, 192]}
  - {name: Stairs, source: raw_int, color: [192, 192, 192]}
  - {name: Door, source: raw_int, color: [192, 192, 192]}
  - {name: Road, source: raw_int, color: [224, 224, 224]}
  - {name: Sidewalk, source: raw_int, color: [224, 224, 224]}
  - {name: Floor, source: raw_int, color: [255, 255, 255]}
  - {name: Wall, source: raw_int, color: [255, 255, 0]}
  - {name: Building, source: raw_int, color: [255, 255, 0]}
  - {name: Signal, source: raw_int, color: [255, 255, 0]}
  - {name: Furniture, source: raw_int, color: [255, 255, 0]}
  - {name: Window, source: raw_int, color: [255, 255, 0]}
  - {name: Structure, source: raw_int, color: [255, 255, 0]}
  - {name: Unknown, source: raw_int, color: [0, 0, 0]}
  - {name: Dynamic_NonHuman, source: raw_int, color: [204, 0, 0]}
  - {name: Human, source: raw_int, color: [204, 0, 0]}
  - {name: Wall_Decoration, source: raw_int, color: [204, 0, 204]}
default_color:
  - 0.9677975592919913
  - 0.44127456009157356
  - 0.5358103155058701
